### ISSUE TITLE
Does not look as in the picture

### ISSUE THREAD

**Issue by Suppresed** [MaxSt/challenger-deep#10]
I melpa and manually installed it. Background is dark grey and letters are the different too

**Comment by MaxSt** [comment]
Can you give me more information about your setup? Are you using emacs in a terminal? If so, what terminal? Does the terminal has 24-bit color support? What version of emacs are you using? Can you post a screenshot?

**Comment by Suppresed** [comment]
i use the terminal version of emacs. emacs -nw. Maybe that's it
