### ISSUE TITLE
Company - can't read annotation in popup

### ISSUE THREAD

**Issue by sebasmonia** [MaxSt/challenger-deep#11]
With default configuration:

![image](https://user-images.githubusercontent.com/1651857/67739690-edd62f80-f9d8-11e9-9c1d-11d0febfbbe6.png)

Tried some alternative from the package (keep in mind I'm not the most design-y person):

![image](https://user-images.githubusercontent.com/1651857/67739767-2c6bea00-f9d9-11e9-941c-648876c1df24.png)

We need to adjust `company-tooltip-annotation`, in my second screenshot I chose `cyan`.
Or, change `company-tooltip-selection`.

Thank you!

**Comment by MaxSt** [comment]
Thanks for reporting this problem! :+1:
I think the proposed `company-tooltip-annotation` color looks good!
Fixed with https://github.com/challenger-deep-theme/emacs/commit/8d18177cbe6a597d59f7ea6a0d5f10aa2d0acafe

**Comment by sebasmonia** [comment]
Awesome, thank you!
