### ISSUE TITLE
tab colors in kitty

### ISSUE THREAD

**Issue by blablablerg** [MaxSt/challenger-deep#15]
Hello, first I want to say I like this theme! Great work

For Kitty terminal, I have added tab colors to fit with the theme:

active_tab_foreground #1e1c31
active_tab_background #cbe3e7
inactive_tab_foreground #1e1e1e
inactive_tab_background #9d9d9d

**Comment by MaxSt** [comment]
:+1: , thank you :heart: 
I updated the kitty theme accordingly: https://github.com/challenger-deep-theme/kitty/commit/86be49a2b5807bf1cbd6fc4c4deb474d0be28ba5
