### ISSUE TITLE
[suggestion] add proper support for diff-hl

### ISSUE THREAD

**Issue by zovt** [MaxSt/challenger-deep#2]
Great theme! Currently using this in my Emacs. However, the diff-hl highlighting blocks show up all in the same color, and are just a thin line without any background color. It would be great if you could implement colors to match the diff-hl statuses.

**Comment by zovt** [comment]
Unsure what happened, but I restarted emacs and now the lines are at least colored correctly according to diff-hl, but there is still no fill.

**Comment by MaxSt** [comment]
thanks for the suggestion! i will look into that on the weekend

**Comment by MaxSt** [comment]
can you post a screenshot? when i tried diff-hl-mode it looked good (additions in green, modifications in yellow and deletions in red)

**Comment by zovt** [comment]
Yes, the lines were colored properly but the background color which filled the diff lines were not filled
