### ISSUE TITLE
Unreadable text in ediff 

### ISSUE THREAD

**Issue by SavchenkoValeriy** [MaxSt/challenger-deep#3]
The text is too pale for red and green background colors.
![screenshot from 2017-06-23 10-50-47](https://user-images.githubusercontent.com/1611696/27471965-4e430b66-5802-11e7-9e12-14b58ae3f5ab.png)

BTW thank you for the theme!

**Comment by MaxSt** [comment]
thank you for the report, i just fix the issue!
I have never used ediff before but now that i have looked into it, i really like it :smile:
