### ISSUE TITLE
[Improvement] Better ivy-subdir and ivy-current-match colors

### ISSUE THREAD

**Issue by gguimaraesbr** [MaxSt/challenger-deep#9]
I'm huge fan of this theme and I would like to suggest a little improvement regarding the display of subdirs in ivy:

![screen shot 2018-08-16 at 17 39 10](https://user-images.githubusercontent.com/66819/44233939-a1a82200-a17b-11e8-8b45-74e6dd0c04f1.png)

P.S.: Could send a PR but I don't know what color would fit better 😄

**Comment by MaxSt** [comment]
Hey, thanks for reporting this :+1: 
I'm also not sure to which color to change. One option would be to change the foreground color of the selection. What do you think?
![new_ivy_color](https://user-images.githubusercontent.com/720801/44234472-f614c700-a1a6-11e8-9e7a-b02ed958f0ea.png)

**Comment by gguimaraesbr** [comment]
👍

**Comment by MaxSt** [comment]
Fixed in https://github.com/challenger-deep-theme/emacs/commit/443ca72dca966b3d27dbec9eab54a09cbd76eac0
